# Generated by Django 4.2.2 on 2023-07-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="estado",
            field=models.BooleanField(default=False),
        ),
    ]
