# Generated by Django 4.2.2 on 2023-07-07 20:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_producto_estado"),
    ]

    operations = [
        migrations.RenameField(
            model_name="producto",
            old_name="estado",
            new_name="activo",
        ),
    ]
