# Generated by Django 4.2.2 on 2023-07-07 21:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_rename_estado_producto_activo"),
    ]

    operations = [
        migrations.CreateModel(
            name="postular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(default="", max_length=200)),
                ("celular", models.IntegerField(blank=True, null=True)),
                ("email", models.CharField(max_length=100)),
                ("fecha", models.DateField(default=django.utils.timezone.now)),
                (
                    "producto",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.producto",
                    ),
                ),
            ],
        ),
    ]
