# Generated by Django 4.2.2 on 2023-07-07 21:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_postular"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postular",
            name="fecha",
        ),
    ]
